export const carData = [
  {
    id: "car_001",
    name: "Mercedes-Benz C220d",
    location: "New South Wales, Australia",
    imageUrl: "/car_image1.png",
    rating: 4.95,
    reviewCount: 672,
    distanceIncluded: "100 miles",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatingCapacity: 4,
    pricePerDay: 498.25,
    availability: true,
    licensePlate: "YF58 ZZT",
    vehicleType: "SUV",
  },
  {
    id: "car_002",
    name: "BMW X3",
    location: "Melbourne, Australia",
    imageUrl: "/car_image2.png",
    rating: 4.8,
    reviewCount: 521,
    distanceIncluded: "120 miles",
    transmission: "Automatic",
    fuelType: "Petrol",
    seatingCapacity: 5,
    pricePerDay: 512.0,
    availability: true,
    licensePlate: "AB12 XYZ",
    vehicleType: "SUV",
  },
  {
    id: "car_003",
    name: "Audi A4",
    location: "Sydney, Australia",
    imageUrl: "/car_image3.png",
    rating: 4.7,
    reviewCount: 450,
    distanceIncluded: "90 miles",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatingCapacity: 5,
    pricePerDay: 475.5,
    availability: true,
    licensePlate: "CD34 EFH",
    vehicleType: "Sedan",
  },
  {
    id: "car_004",
    name: "Tesla Model 3",
    location: "Brisbane, Australia",
    imageUrl: "/car_image3.png",
    rating: 4.9,
    reviewCount: 830,
    distanceIncluded: "150 miles",
    transmission: "Automatic",
    fuelType: "Electric",
    seatingCapacity: 5,
    pricePerDay: 620.0,
    availability: true,
    licensePlate: "EV88 PWR",
    vehicleType: "Sedan",
  },
  {
    id: "car_005",
    name: "Hyundai Tucson",
    location: "Adelaide, Australia",
    imageUrl: "/car_image2.png",
    rating: 4.6,
    reviewCount: 390,
    distanceIncluded: "100 miles",
    transmission: "Automatic",
    fuelType: "Petrol",
    seatingCapacity: 5,
    pricePerDay: 450.0,
    availability: true,
    licensePlate: "GH56 JKL",
    vehicleType: "SUV",
  },
  {
    id: "car_006",
    name: "Mazda CX-5",
    location: "Canberra, Australia",
    imageUrl: "/car_image1.png",
    rating: 4.85,
    reviewCount: 520,
    distanceIncluded: "110 miles",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatingCapacity: 5,
    pricePerDay: 480.75,
    availability: true,
    licensePlate: "MN78 OPQ",
    vehicleType: "SUV",
  },
  {
    id: "car_007",
    name: "Toyota Corolla",
    location: "Gold Coast, Australia",
    imageUrl: "/car_image1.png",
    rating: 4.4,
    reviewCount: 315,
    distanceIncluded: "80 miles",
    transmission: "Manual",
    fuelType: "Petrol",
    seatingCapacity: 5,
    pricePerDay: 380.0,
    availability: true,
    licensePlate: "RS90 TUV",
    vehicleType: "Hatchback",
  },
  {
    id: "car_008",
    name: "Nissan X-Trail",
    location: "Hobart, Australia",
    imageUrl: "/car_image2.png",
    rating: 4.55,
    reviewCount: 400,
    distanceIncluded: "100 miles",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatingCapacity: 7,
    pricePerDay: 520.0,
    availability: true,
    licensePlate: "WX12 YZA",
    vehicleType: "SUV",
  },
  {
    id: "car_009",
    name: "Kia Sportage",
    location: "Perth, Australia",
    imageUrl: "/car_image3.png",
    rating: 4.65,
    reviewCount: 375,
    distanceIncluded: "105 miles",
    transmission: "Automatic",
    fuelType: "Petrol",
    seatingCapacity: 5,
    pricePerDay: 455.0,
    availability: true,
    licensePlate: "ZB34 CDE",
    vehicleType: "SUV",
  },
  {
    id: "car_010",
    name: "Ford Ranger",
    location: "Darwin, Australia",
    imageUrl: "/car_image2.png",
    rating: 4.75,
    reviewCount: 460,
    distanceIncluded: "130 miles",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatingCapacity: 5,
    pricePerDay: 540.0,
    availability: true,
    licensePlate: "FG56 HIJ",
    vehicleType: "Pickup",
  },
  {
    id: "car_011",
    name: "Volkswagen Golf",
    location: "Sydney, Australia",
    imageUrl: "/car_image1.png",
    rating: 4.5,
    reviewCount: 350,
    distanceIncluded: "90 miles",
    transmission: "Automatic",
    fuelType: "Petrol",
    seatingCapacity: 5,
    pricePerDay: 410.0,
    availability: true,
    licensePlate: "KL78 MNO",
    vehicleType: "Hatchback",
  },
  {
    id: "car_012",
    name: "Subaru Forester",
    location: "Newcastle, Australia",
    imageUrl: "/car_image3.png",
    rating: 4.7,
    reviewCount: 405,
    distanceIncluded: "100 miles",
    transmission: "Automatic",
    fuelType: "Petrol",
    seatingCapacity: 5,
    pricePerDay: 495.0,
    availability: true,
    licensePlate: "PQ90 RST",
    vehicleType: "SUV",
  },
  {
    id: "car_013",
    name: "Honda CR-V",
    location: "Geelong, Australia",
    imageUrl: "/car_image1.png",
    rating: 4.6,
    reviewCount: 375,
    distanceIncluded: "95 miles",
    transmission: "Automatic",
    fuelType: "Petrol",
    seatingCapacity: 5,
    pricePerDay: 470.0,
    availability: true,
    licensePlate: "UV12 WXY",
    vehicleType: "SUV",
  },
  {
    id: "car_014",
    name: "Jeep Wrangler",
    location: "Cairns, Australia",
    imageUrl: "/car_image3.png",
    rating: 4.3,
    reviewCount: 298,
    distanceIncluded: "110 miles",
    transmission: "Manual",
    fuelType: "Diesel",
    seatingCapacity: 5,
    pricePerDay: 530.0,
    availability: true,
    licensePlate: "XZ45 YLM",
    vehicleType: "SUV",
  },
  {
    id: "car_015",
    name: "Peugeot 3008",
    location: "Toowoomba, Australia",
    imageUrl: "/car_image2.png",
    rating: 4.65,
    reviewCount: 334,
    distanceIncluded: "100 miles",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatingCapacity: 5,
    pricePerDay: 460.0,
    availability: true,
    licensePlate: "GH76 KPR",
    vehicleType: "SUV",
  },
];
