export const orderData = [
  { _id: 1, name: "Toyota Corolla", pick_up_location: "New York", drop_off_location: "New York", date: "March 2, 2025", return_date: "March 4, 2025", status: "scheduled" },
  { _id: 2, name: "Honda Civic", pick_up_location: "Los Angeles", drop_off_location: "Los Angeles", date: "March 3, 2025", return_date: "March 5, 2025", status: "completed" },
  { _id: 3, name: "Ford Focus", pick_up_location: "Chicago", drop_off_location: "Chicago", date: "March 4, 2025", return_date: "March 6, 2025", status: "canceled" },
  { _id: 4, name: "Hyundai Elantra", pick_up_location: "Miami", drop_off_location: "Miami", date: "March 5, 2025", return_date: "March 7, 2025", status: "scheduled" },
  { _id: 5, name: "Nissan Sentra", pick_up_location: "Seattle", drop_off_location: "Seattle", date: "March 6, 2025", return_date: "March 8, 2025", status: "completed" },
  { _id: 6, name: "Kia Forte", pick_up_location: "San Francisco", drop_off_location: "San Francisco", date: "March 7, 2025", return_date: "March 9, 2025", status: "canceled" },
  { _id: 7, name: "Mazda 3", pick_up_location: "Dallas", drop_off_location: "Dallas", date: "March 8, 2025", return_date: "March 10, 2025", status: "scheduled" },
  { _id: 8, name: "Volkswagen Jetta", pick_up_location: "Atlanta", drop_off_location: "Atlanta", date: "March 9, 2025", return_date: "March 11, 2025", status: "completed" },
  { _id: 9, name: "Chevrolet Cruze", pick_up_location: "Denver", drop_off_location: "Denver", date: "March 10, 2025", return_date: "March 12, 2025", status: "canceled" },
  { _id: 10, name: "Subaru Impreza", pick_up_location: "Boston", drop_off_location: "Boston", date: "March 11, 2025", return_date: "March 13, 2025", status: "scheduled" },
  { _id: 11, name: "Toyota Camry", pick_up_location: "New York", drop_off_location: "New York", date: "March 12, 2025", return_date: "March 14, 2025", status: "completed" },
  { _id: 12, name: "Honda Accord", pick_up_location: "Los Angeles", drop_off_location: "Los Angeles", date: "March 13, 2025", return_date: "March 15, 2025", status: "canceled" },
  { _id: 13, name: "Ford Fusion", pick_up_location: "Chicago", drop_off_location: "Chicago", date: "March 14, 2025", return_date: "March 16, 2025", status: "scheduled" },
  { _id: 14, name: "Hyundai Sonata", pick_up_location: "Miami", drop_off_location: "Miami", date: "March 15, 2025", return_date: "March 17, 2025", status: "completed" },
  { _id: 15, name: "Nissan Altima", pick_up_location: "Seattle", drop_off_location: "Seattle", date: "March 16, 2025", return_date: "March 18, 2025", status: "canceled" },
  { _id: 16, name: "Kia Optima", pick_up_location: "San Francisco", drop_off_location: "San Francisco", date: "March 17, 2025", return_date: "March 19, 2025", status: "scheduled" },
  { _id: 17, name: "Mazda 6", pick_up_location: "Dallas", drop_off_location: "Dallas", date: "March 18, 2025", return_date: "March 20, 2025", status: "completed" },
  { _id: 18, name: "Volkswagen Passat", pick_up_location: "Atlanta", drop_off_location: "Atlanta", date: "March 19, 2025", return_date: "March 21, 2025", status: "canceled" },
  { _id: 19, name: "Chevrolet Malibu", pick_up_location: "Denver", drop_off_location: "Denver", date: "March 20, 2025", return_date: "March 22, 2025", status: "scheduled" },
  { _id: 20, name: "Subaru Legacy", pick_up_location: "Boston", drop_off_location: "Boston", date: "March 21, 2025", return_date: "March 23, 2025", status: "completed" },
];
